name: Simple Manual Workflow - Environment

# controls the action will run
on:
  # Allows the workflow to run manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DEV:
    # the type of runner the job will run on
    runs-on: ubuntu-latest
    environment: dev-env

    # sequence of task executed as part of the job
    steps:
      # checks out your repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a script in DEV
        run: |
          echo "I am running job in dev-env environment under DEV job"
          echo "this is environment secret ${{secrets.ENV_SECRET}}"
          echo "trying to fetch repo secret inside the environment which is overriden by environment secret ${{secrets.ENV_SECRET}}"
          echo "this is environment variable ${{vars.ENV_VAR}}"
          echo "trying to fetch repo variable inside the environment which is overriden by environment variable ${{vars.ENV_VAR}}"

  QA:
    runs-on: ubuntu-latest
    needs: [DEV]
    steps:
      - uses: actions/checkout@v4

      - name: run a script in QA
        run: |
          echo "I am running job under QA job"
          echo "this is repo secret ${{secrets.ENV_SECRET}}"
          echo "this is repo variable ${{vars.ENV_VAR}}"
