# https://github.com/orgs/community/discussions/154396)
# reference issue
name: Tag on PR close

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: set TAG_NAME
        id: tag_name
        run: echo "TAG_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Authenticate with github App
        id: auth
        # https://github.com/tibdex/github-app-token?tab=readme-ov-file - deprecated
        # https://github.com/actions/create-github-app-token?tab=readme-ov-file
        uses: actions/create-github-app-token@v2
        # uses: tibdex/github-app-token@v2.1.0 # deprecated use actions/create-github-app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo $TAG_NAME
          git tag $TAG_NAME
          git push https://x-access-token:${{ steps.auth.outputs.token }}@github.com/${{ github.repository }}.git $TAG_NAME
